// Use ISO alpha-3 country codes, see e.g. https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3
COUNTRIES =
{
    PRT: {fillKey: 'visited'},
    ESP: {fillKey: 'visited'},
    FRA: {fillKey: 'visited'},
    GBR: {fillKey: 'visited'},
    BEL: {fillKey: 'visited'},
    NLD: {fillKey: 'visited'},
    CHE: {fillKey: 'visited'},
    ITA: {fillKey: 'visited'},
    DEU: {fillKey: 'visited'},
    CZE: {fillKey: 'visited'},
    AUT: {fillKey: 'visited'},
    HRV: {fillKey: 'visited'},
    BIH: {fillKey: 'visited'},
    GRC: {fillKey: 'visited'},
    HUN: {fillKey: 'visited'},
    SWE: {fillKey: 'visited'},
    DNK: {fillKey: 'visited'},
    NOR: {fillKey: 'visited'},
    MAR: {fillKey: 'visited'},
    TUR: {fillKey: 'visited'},
    DOM: {fillKey: 'visited'},
    THA: {fillKey: 'visited'},
}
